version: '3'
networks:
  web-network:

services:
  verapdf:
    image: darrenopf/verapdf-rest:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - web-network